### ISSUE TITLE
Results are conflict with the paper

### ISSUE THREAD

**Issue by wxywhu** [shuozh/resLF#5]
Dear author, thank you for the pre-trained model. I tested the method on Buddha and Moha image 
 in a mat format (9x9x768x768x3), using bicubic interpolation in matlab. However, I got the results: avg.x2 Buddha: 39.82/0.9825 Moha:41.19/0.9878, which is conflicted with the paper results. The only difference is the original data and I notice your data format is png. Does it matter much? 
Additionally, I trained the EDSR on the LF dataset(250) and the result: avg.x2 Buddha: 39.83/0.9844 Moha:41.66/0.9898.

**Comment by shuozh** [comment]
The input data should be the original high-resolution image, since we downsampled it in the preprocessing  using different downsampling  methods and recover it from H*W to 2*H*2*W directly in the network. Therefore, no more bicubic interpolation is needed. 
We did not retrain the EDSR using the LF dataset since we consider EDSR should be trained with more images in order to obtain a better performances.
